### ISSUE TITLE
--follow does not show redirects

### ISSUE THREAD

**Issue by vartec** [jkbrzt/httpie#183]
I've expected `http --follow` to act in similar fashion as `curl -i -L`, however difference is that curl does show headers of all intermediate steps, httpie does not.

Expected result (standard post-redirect-get form):
```
HTTP/1.1 100 Continue

HTTP/1.1 303 See Other
Content-Type: text/html; charset=UTF-8
Date: Fri, 29 Nov 2013 11:50:59 GMT
Location: http://other.test.server/
Server: nginx/1.1.19
Content-Length: 0
Connection: keep-alive

HTTP/1.1 200 OK
Date: Fri, 29 Nov 2013 11:51:00 GMT
Server: Apache/2.2.14 (Ubuntu)
Vary: Accept-Encoding,Cookie
Pragma: no-cache
Cache-Control: private, max-age=0, must-revalidate
Transfer-Encoding: chunked
Content-Type: application/json

{"payload": "something"}
```
Actual result:
```
HTTP/1.1 200 OK
Cache-Control: private, max-age=0, must-revalidate
Content-Encoding: gzip
Content-Length: 414
Content-Type: application/json
Date: Fri, 29 Nov 2013 11:55:34 GMT
Pragma: no-cache
Server: Apache/2.2.14 (Ubuntu)
Vary: Accept-Encoding,Cookie

{"payload": "something"}
```

**Comment by ralphschindler** [comment]
:+1:

**Comment by rockymadden** [comment]
Looking for this as well. Currently using a custom bash function to accommodate.

**Comment by ian-rose** [comment]
This would be _very_ useful functionality to have.

**Comment by tylercrompton** [comment]
I'll redo this if @jakubroztocil would review the changes. But after a year, there were too many conflicts and it didn't seem like it would ever get reviewed, so I just deleted what I did.

**Comment by dstarmanhr** [comment]
this would be a very useful feature to have.

**Comment by jlazic** [comment]
+1 for this feature.

**Comment by jonoden** [comment]
+1

**Comment by jbenoit2011** [comment]
+1 for that feature. Thanks.

**Comment by sgoblin** [comment]
Can you give a brief summary of how you implemented this, @tylercrompton ?

**Comment by jcdevil** [comment]
+1 for that feature. Thanks ;)

**Comment by victorgama** [comment]
+1 for that.

**Comment by Wirone** [comment]
@jkbrzt was `--show-redirects` merged? I've updated to 0.9.6 and I get "http: error: unrecognized arguments: --show-redirects"..

**Comment by jkbrzt** [comment]
@Wirone yes, it's called `--all` — https://github.com/jkbrzt/httpie#viewing-intermediary-requests-responses

**Comment by Remzi1993** [comment]
@jakubroztocil `--all` doesn't work for me, I try to do: `http --all -v :3000`
