### ISSUE TITLE
When used as ssh command, http hangs on empty stdin  

### ISSUE THREAD

**Issue by robertjustjones** [jkbrzt/httpie#190]
This is related to #150 addressed with the --ignore-stdin switch.

When doing the following, httpie assumes a POST and hangs since stdin is piped but empty.
```
ssh 192.168.1.1 http :8080       # hangs, but I love the new syntax!
```

The following works as expected, but is verbose.
```
ssh 192.168.1.1 http --ignore-stdin :8080     
```

Can HTTPie be made to detect that stdin is empty and not assume a POST here?

**Comment by jkbrzt** [comment]
The development version of HTTPie now supports `-I` as a shortcut for `--ignore-stdin`.
