### ISSUE TITLE
Advanced stdin processing

### ISSUE THREAD

**Issue by Valodim** [jkbrzt/httpie#194]
Hey there,

I am missing a feature to pass a file as a post field from stdin. My particular use case is this from curl:
  command | curl -F 'sprunge=<-' http://sprunge.us
which I noticed is not possible with httpie.

If it's not too much trouble, I would kindly like to request this feature.

**Comment by saintdev** [comment]
Hi, I came across this because I was also attempting to use the sprunge.us service with httpie, but not from within vim. Could this be reopened? Passing data via a pipe still doesn't work.

```
$ http --version
0.8.0

$ dmesg | http -f sprunge.us sprunge=@/dev/stdin
usage: http [--json] [--form] [--pretty {all,colors,format,none}]
            [--style STYLE] [--print WHAT] [--verbose] [--headers] [--body]
            [--stream] [--output FILE] [--download] [--continue]
            [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH]
            [--auth USER[:PASS]] [--auth-type {basic,digest}]
            [--proxy PROTOCOL:PROXY_URL] [--follow] [--verify VERIFY]
            [--timeout SECONDS] [--check-status] [--ignore-stdin] [--help]
            [--version] [--traceback] [--debug]
            [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
http: error: Request body (from stdin or a file) and request data (key=value) cannot be mixed.
```

**Comment by jkbrzt** [comment]
This is now being worked on here: #370

**Comment by jaraco** [comment]
I also would like this feature. I'm grabbing a CSV, posting it to a service, altering the CSV using csvkit, and then want to post the altered version to a service again:

```
http -f POST http://ourservice/ action=decode file@identifiers.csv | csvcut -c DECODED | http -f POST http://ourcsvservice/ action=encode file@/dev/stdin --ignore-stdin
```

It would be nice to have been able to use `file@-` and not have to supply `--ignore-stdin`.

**Comment by cognivore** [comment]
Agreed, @jaraco
