### ISSUE TITLE
Content Type of file uploaded in multipart/form-data request

### ISSUE THREAD

**Issue by myroslav** [jkbrzt/httpie#271]
curl support file Content-Type  via following syntax:

    curl --form "file=@page.pdf;type=application/pdf" http://httpbin.org/post
    {
      "args": {}, 
      "data": "", 
      "files": {
        "file":
    "data:application/pdf;base64,H4sICI0fXVQAA3BhZ2UucGRmAAvOz01VCE7MLchJVQhITE8FAAyOwbUQAAAA"
      }, 
      "form": {}, 
      "headers": {
        "Accept": "*/*", 
        "Connect-Time": "1", 
        "Connection": "close", 
        "Content-Length": "236", 
        "Content-Type": "multipart/form-data;
        boundary=------------------------7d87eceb5520850c", 
        "Host": "httpbin.org", 
        "Total-Route-Time": "0", 
        "User-Agent": "curl/7.32.0", 
        "Via": "1.1 vegur", 
        "X-Request-Id": "9f20c4bc-343b-4bc2-814d-9b2b9de75f83"
      }, 
      "json": null, 
      "origin": "213.130.19.243", 
      "url": "http://httpbin.org/post"
    }

It look like the content it generates is something like:

    POST /post HTTP/1.1
    Accept: */*
    Accept-Encoding: gzip, deflate
    Content-Type: multipart/form-data; boundary=38516d25820c4a9aad05f1e42cb442f4
    Host: httpbin.org

    --38516d25820c4a9aad05f1e42cb442f4
    Content-Disposition: form-data; name="file"; filename="page.pdf"
    Content-Type: application/pdf
    Content-Encoding: base64

    H4sICI0fXVQAA3BhZ2UucGRmAAvOz01VCE7MLchJVQhITE8FAAyOwbUQAAAA
    --38516d25820c4a9aad05f1e42cb442f4--

And I cannot achieve the same result in HTTPie. Any hints are appreciated.

**Comment by jeltz** [comment]
Would it be possible to use a curl-like syntax with semicolon?

    curl -F "web=@index.html;type=text/html" url.com

**Comment by jakubroztocil** [comment]
@jeltz yes, good idea

**Comment by wodny** [comment]
Hi, I've pushed a refined version of PR #285 - PR #398 so it gets green light on TravisCI.

**Comment by cutz** [comment]
@jkbrzt any update on getting #398 merged? I'd be willing to take a stab at a pull request to support specifying the type as part of the value if you are waiting on that.

**Comment by igorspasic** [comment]
yeah, it would be cool if this thing can get in. do you know when?

**Comment by jocull** [comment]
+1

**Comment by lpellegr** [comment]
:+1:

**Comment by eskatos** [comment]
:tada: 
Thanks!
