### ISSUE TITLE
Error when using command substitution

### ISSUE THREAD

**Issue by ajmichels** [jkbrzt/httpie#340]
I get the following line in the response headers when I attempt to using command substitution when executing HTTPie:

`ttp: error: IOError: [Errno 35] Resource temporarily unavailable`

Here is an example of what I am trying to do:

`http get mysite.com myarg=$(my-command 'some arg')`

The request headers and body look correct, it is just the response that is messed up. The response headers look like they are getting cut off and there is no response body.

---

I am running HTTPie v0.9.2 with Python v2.7.8 on Mac OSX v10.10.3

**Comment by jkbrzt** [comment]
@ajmichels tou probably need to quote the argument:

```sh
$ http get mysite.com myarg="$(my-command 'some arg')"
```

Read more about this here: http://tldp.org/LDP/abs/html/quotingvar.html
