### ISSUE TITLE
Cannot install httpie via pip in Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by k0pernikus** [jkbrzt/httpie#354]
Installing `httpie` via `sudo pip install --upgrade httpie` leads to:

        $ http
	Traceback (most recent call last):
	  File "/usr/local/bin/http", line 7, in <module>
	    from httpie.__main__ import main
	  File "/usr/local/lib/python2.7/dist-packages/httpie/__main__.py", line 6, in <module>
	    from .core import main
	  File "/usr/local/lib/python2.7/dist-packages/httpie/core.py", line 22, in <module>
	    from httpie.client import get_response
	  File "/usr/local/lib/python2.7/dist-packages/httpie/client.py", line 6, in <module>
	    from requests.packages import urllib3
	ImportError: No module named packages

Intalling it via `apt-get install httpie` at least gets version `0.8` working.

**Comment by DarKnight--** [comment]
Update requests and Pygments then try updating httpie.

**Comment by CMCDragonkai** [comment]
I got this error recently. It was actually working prior to me installing pip and then installing awscli. I installed it from `easy_install`.

```
Traceback (most recent call last):
  File "/usr/local/bin/http", line 9, in <module>
    load_entry_point('httpie==0.9.2', 'console_scripts', 'http')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/httpie/__main__.py", line 6, in <module>
    from .core import main
  File "/usr/local/lib/python2.7/dist-packages/httpie/core.py", line 22, in <module>
    from httpie.client import get_response
  File "/usr/local/lib/python2.7/dist-packages/httpie/client.py", line 6, in <module>
    from requests.packages import urllib3
ImportError: No module named packages
```

Even after updating requests and pygments, it still fails.

**Comment by AllanDaemon** [comment]
Same here: same error, ubuntu 14.04 too, latest version of httpie. In my case I'm on a almost fresh install of ubuntu, and I tried to install instead of update.

pigments, urllib3, requests are fully updated using pip.

**Comment by imacleod** [comment]
Hmm "pip install --upgrage httpie" worked for me in Ubuntu 14.04 in a fresh virtualenv:
"Installing collected packages: requests, Pygments, httpie
Successfully installed Pygments-2.0.2 httpie-0.9.2 requests-2.7.0"

**Comment by k0pernikus** [comment]
Still breaking for me. 

@imacleod What do you mean by fresh a virtualenv? Could you please elaborate on how you got it working?

**Comment by imacleod** [comment]
@k0pernikus By a fresh virtualenv I meant creating a new virtualenv, activating it, and installing httpie inside of it. I just did this again with a new virtualenv to confirm that it worked and it did. I used these steps:

    virtualenv testenv
    cd testenv
    source bin/activate
    pip install --upgrade httpie

**Comment by webaaz** [comment]
I've got the same error.
But after installing Pygments and Requests I got the the following error :
> httpie error: TypeError: __str__ returned non-string (type Error)

It's ok with a : 
> --verify=no

**Comment by jakubroztocil** [comment]
I've tested both `apt-get install httpie` and `pip install httpie` on a fresh Ubuntu 14.04.2 instance but haven't been able to reproduce this issue.

**Comment by rainyday** [comment]
running `pip install --upgrade requests` fixed this issue for me.

**Comment by emi-silva** [comment]
Make sure you have installed `requests` by means of `pip`:
```bash
sudo apt-get remove python-requests python3-requests
```
