### ISSUE TITLE
New feature: JMESPath filter on results

### ISSUE THREAD

**Issue by jeremyplichta** [jkbrzt/httpie#367]
It would be really useful if you could pass an argument to httpie that would filter the results of the JSON it received using a JMESPath expression (http://jmespath.org/). This would be similar to how the AWS CLI works with the --query option (http://docs.aws.amazon.com/cli/latest/userguide/controlling-output.html).

If there is interest in this and people think it would be worthwhile I might look into it and submit a pull request when I have some time.

**Comment by jkbrzt** [comment]
@jeremyplichta advanced content manipulation is not really something httpie should itself. You can, however, easily use httpie in with other tools, such as [jq](https://stedolan.github.io/jq/).

**Comment by jeremyplichta** [comment]
Thanks, wasn't aware of that tool at the time but have since found it!
