### ISSUE TITLE
example.localhost is a unknown host

### ISSUE THREAD

**Issue by kelunik** [jkbrzt/httpie#373]
HTTPie can't resolve subdomains of `localhost`, but browsers can. A request to `http://example.localhost/` results in a hostname not found error.

**Comment by zahradil** [comment]
I do not get what is wrong. At my machine, `example.localhost` is unresolvable and *hostname not found error* is IMO **correctly** returned. Also my browser does not know this domain, therefore I believe that this behaviour is correct.

**Comment by kelunik** [comment]
My browser (Chromium) automatically resolves all subdomains of `localhost` to `localhost`, which is pretty useful for testing things, because you don't have to add an entry to `/etc/hosts` every time.

**Comment by zahradil** [comment]
I've just tested it: 

- Google Chrome - as you report, it resolves example.localhost to 127.0.0.1
- Firefox - hostname not found
- Microsoft Edge - hostname not found

It seems it is supported in Chrome/Chromium only.

**Comment by zahradil** [comment]
I recommend the straitforward solution - you can use `lvho.st` instead of `localhost`:

- example.lvho.st
- subdomain2.lvho.st
- etc.

It already works with httpie and all browsers.

**Comment by jkbrzt** [comment]
@kelunik I can see how this is useful. However, I don't think this fallback is suitable for such a low-level tool as httpie is.

**Comment by joeblubaugh** [comment]
`curl` now resolves localhost domains in this fashion. It's in RFC 6761. I've created a feature request to support this at #1458
