### ISSUE TITLE
how to add request body for GET request? needed for elasticsearch restful-api call?

### ISSUE THREAD

**Issue by hackrole** [jkbrzt/httpie#380]
the elasticsearch api may add request body for get. like this.
```bash
curl -XGET 'http://localhost:9200/_count?pretty' -d '
{
    "query": {
        "match_all": {}
    }
}
'
```
but the httpie seems not allow such usage.

**Comment by jkbrzt** [comment]
HTTPie makes possible to specify request body for any HTTP method, including GET.  In your case, passing it [via `STDIN`](https://github.com/jkbrzt/httpie#redirected-input) is probably the best way to go:

```sh
$ echo '{"query": {"match_all": {}}}' | http GET :9200/_count?pretty
```

**Comment by hackrole** [comment]
thanks
