### ISSUE TITLE
Curl mode

### ISSUE THREAD

**Issue by MichaelMackus** [jkbrzt/httpie#383]
I'm wondering if there's a way to do a straight CURL request in Httpie. This would be very useful with long curl requests that I would like to see the pretty output from.

Even just a way to pipe curl -> httpie would be cool

Any ideas?

**Comment by sigmavirus24** [comment]
`httpie` is not (just) a formatter; it is (also) an HTTP client. If you want the pretty output (sans colorization) you can use `python -m json.tool` or `jq`.

**Comment by MichaelMackus** [comment]
Thanks I'll look into those!

**Comment by MichaelMackus** [comment]
Closing since the following works fine for my use case:

`curl CURL_FROM_FIREFOX | python -m json.tool`
