### ISSUE TITLE
--verify with IP address SAN-s result in SSLError

### ISSUE THREAD

**Issue by kissgyorgy** [jkbrzt/httpie#388]
Verifying a certificate which have Subject Alternative Names with IP addresses, Common Name should not be checked and those addresses should be checked instead.
[RFC 6125 describe this](http://tools.ietf.org/html/rfc6125#section-6.4.4)

This is probably a bug in urrlib3 (if you use it :smile:), see https://github.com/kennethreitz/requests/issues/2781

**Comment by sigmavirus24** [comment]
@kissgyorgy it is a bug in requests & urllib3 (the former relies on the latter). It looks like it's increasingly becoming an issue and someone will have to prioritize working on it.

/cc @Lukasa

**Comment by Lukasa** [comment]
Yeah, this is a known bug and it's a *pain in the neck*.

**Comment by jkbrzt** [comment]
https://twitter.com/kissgyorgy/status/780342969622671360

**Comment by kissgyorgy** [comment]
If you are curious, the pull request that solves this is shazow/urllib3#922 which solves the issue shazow/urllib3#258
