### ISSUE TITLE
Maven pom.xml files become namespaced when accessed with httpie

### ISSUE THREAD

**Issue by rombert** [jkbrzt/httpie#389]
With 

     http https://repo1.maven.org/maven2/org/apache/apache/17/apache-17.pom

the whole XML document receives a ns0 namespace. Contrast ( httpie )

    <?xml version="1.0" encoding="UTF-8"?>
    <ns0:project xmlns:ns0="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <ns0:modelVersion>4.0.0</ns0:modelVersion>
        <ns0:groupId>org.apache</ns0:groupId>

with ( curl)

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
      <modelVersion>4.0.0</modelVersion>
      <groupId>org.apache</groupId>
      <artifactId>apache</artifactId>

Comments are also lost, but not shown here for brevity

**Comment by analytically** [comment]
+1

**Comment by jkbrzt** [comment]
Please follow #443
