### ISSUE TITLE
Unable to use form parameters with colon in their names

### ISSUE THREAD

**Issue by rombert** [jkbrzt/httpie#390]
I'm trying to POST a form parameter named sling:target, but http always considers it a header. For the following call 

    http -v -f POST localhost:8080 sling:target=/system/console/bundles

A `sling: target=/system/console/bundles` header is always generated. I also tried

* sling\:target=/system/console/bundles
* 'sling:target'=/system/console/bundles
* "sling:target"=/system/console/bundles

but they all have the same effect

**Comment by jkbrzt** [comment]
@rombert, please see:

> You can use `\` to escape characters that shouldn't be used as separators (or parts thereof). For instance, `foo\==bar` will become a data key/value pair (`foo=` and `bar`) instead of a URL parameter.

https://github.com/jkbrzt/httpie#request-items

**Comment by rombert** [comment]
@jkbrzt  - thanks for the pointer to the docs. A simple escape does not work, e.g. `sling\:target=/system/console/bundles`. However, double-escaping works: `sling\\:target=/system/console/bundles`.

Is that expected?

**Comment by jkbrzt** [comment]
@rombert yes, it's because the arguments go through the your shell which also uses \escaping. You can put the argument in quotes to avoid double escaping:

```
'sling\:target=/system/console/bundles'
```

**Comment by rombert** [comment]
Makes sense, thank you
