### ISSUE TITLE
AttributeError: 'module' object has no attribute 'disable_warnings'

### ISSUE THREAD

**Issue by mattotodd** [jkbrzt/httpie#391]
Just read about this and tried the example but get the following error   on OSX 10.10.1

jiminy-cricket:src mattotodd$ http http://radek.io/
Traceback (most recent call last):
  File "/usr/local/bin/http", line 7, in <module>
    from httpie.__main__ import main
  File "/Library/Python/2.7/site-packages/httpie/__main__.py", line 6, in <module>
    from .core import main
  File "/Library/Python/2.7/site-packages/httpie/core.py", line 22, in <module>
    from httpie.client import get_response
  File "/Library/Python/2.7/site-packages/httpie/client.py", line 15, in <module>
    urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'disable_warnings'

**Comment by KLuka** [comment]
See #316 for help :wink:

**Comment by mattotodd** [comment]
k, so after reviewing #316 i saw that i was running requests 2.3.0, after running

    pip install --upgrade  requests

this was resolved, thx

**Comment by hangtwenty** [comment]
`pip install --upgrade urllib3` may also be necessary for some users

**Comment by tilek** [comment]
Thanks, Matt. I tried that and here is the problem I encounter: https://stackoverflow.com/questions/53980997/how-to-overcome-dependency-issues-while-upgrading-python-requests-module-on-amaz
