### ISSUE TITLE
README.rst - On mac httpie can also be installed using port (MacPorts).

### ISSUE THREAD

**Issue by jlinoff** [jkbrzt/httpie#395]
Thank you for developing this.

On Mac, httpie can also be installed using port (https://www.macports.org/) as follows:

```bash
$ port install httpie
```

**Comment by conradwt** [comment]
@jlinoff Where does thie port get installed because it doesn't appear within the /opt/local/bin directory?

**Comment by jlinoff** [comment]
This is a python package so it is installed in the site-packages area for the version of python that you are using.

The current default for httpie is python34 so it will be installed in <macports-root>/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/httpie. In my case, <macports-root> is /opt/macports so it is in `/opt/macports//Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/httpie`.

You can access it like this:
```python
$ python3.4
Python 3.4.4 (default, Feb 24 2016, 18:24:59) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import httpie
>>> quit()
```

**Comment by jay-ouellette** [comment]
How do i run it from the CLI?

I want to type `httpie --version` in a terminal

mine got installed to /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httpie

**Comment by jakubroztocil** [comment]
@jay-ouellette the command is simply `http`:

```bash
$ http --version
```
