### ISSUE TITLE
Send data that isn't in key:value form

### ISSUE THREAD

**Issue by looterz** [jkbrzt/httpie#399]
Currently, to send data as the body of a POST you must use key=value , sometimes you need to send data as is with no key assigned - for instance, encrypted or encoded strings, I haven't found a way to do this without piping the data in via a file.

This breaks
```
http -v -f POST server someencodedstring
```

This works
```
http -v -f POST server < payload.file
```

**Comment by hlship** [comment]
This is important to me as well; we're starting to use GraphQL (https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html), but there's no way to say "and include this literal string as the data".  

A workaround:

    echo '...graqhql request data...' | http post ..server.. content-type:application/graphql

**Comment by looterz** [comment]
Maybe a switch for "raw" data that has another condition [here](https://github.com/jkbrzt/httpie/blob/1ded5c2a970cb5b98a2fa98d65ff10aa2068b91b/httpie/input.py#L304-L308) to accept it.

**Comment by jkbrzt** [comment]
The way to do this is is via piping.

https://github.com/jkbrzt/httpie#redirected-input
