### ISSUE TITLE
Support Django Token Auth

### ISSUE THREAD

**Issue by kowsari** [jkbrzt/httpie#405]
I find httpie really useful. It would be great if you/somebody could add Token Auth Plugin. 
http://www.django-rest-framework.org/api-guide/authentication/

It seems straightforward enough and I could develop it...but not sure how to extract and persist the token in the plugin for the session.

**Comment by sigmavirus24** [comment]
Do you mean JSON Web Token Auth? That's the only reference to tokens on that page.

**Comment by kowsari** [comment]
I think JSON Web Token Auth is different than what Django Rest Framework Token Auth is. For Django you login and it sends back an auth_token and then from that point on you send back the token to the server using the Header 'Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b' etc.

Does httpie do this internally using sessions? If so how does it grab it out of the response and put it in the session? Or would we have to develop a plugin for this?

**Comment by hoatle** [comment]
@kowsari this issue should support your case: https://github.com/teracyhq/httpie-jwt-auth/issues/5

Normally, we need to have the token available then use http-jwt-auth plugin to make requests with that token. By default, the auth prefix is "Bearer {token}", in the case of DRF, use "Token {token}" authorization header instead.

The issue I'm working on only supports environment variable for now, not yet argument option. See more: https://github.com/teracyhq/httpie-jwt-auth/tree/develop#faqs the number 2.
