### ISSUE TITLE
Pretty Print JSON Body

### ISSUE THREAD

**Issue by loretoparisi** [jkbrzt/httpie#410]
How to pretty print a JSON output body in order to format it in bash console like

```shell
macbookproloreto:~ admin$ echo '{"foo": "lorem", "bar": "ipsum"}' | python -m json.tool
{
    "bar": "ipsum",
    "foo": "lorem"
}
```

My command looks like now

```shell
http --session=cookies.txt --pretty all --json --print=b --style=xcode "https://myapi.company.com | python -m json.tool
```

Does the option ```--pretty``` aims to pretty print the output body? Having it seems to not prettify the output body, instead it prints the json as plain text

```
'{"foo": "lorem", "bar": "ipsum"}'
```

**Comment by jkbrzt** [comment]
This works out of the box:

![screen shot 2016-01-01 at 6 58 34 pm](https://cloud.githubusercontent.com/assets/326885/12072356/b03f145a-b0b9-11e5-808b-28da7ac1389f.png)

**Comment by loretoparisi** [comment]
@jkbrzt yes but this is not the response ```body```. It seems it does not pretty the body but only the ```headers```.

**Comment by jkbrzt** [comment]
@loretoparisi it is the response body, see http://httpbin.org/get

**Comment by loretoparisi** [comment]
Ok I have found the issue, it's something wrong in the response headers. In fact if I try a well formatted response body with json format like:

```shell
http --session=cookies.txt --pretty all --json --print=b --style=xcode "https://api.spotify.com/v1/tracks/0eGsygTp906u18L0Oimnem"
```

it works. 
When the http response headers are ```text/plain```

```shell
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 1996
Content-Type: text/plain; charset=utf-8
```

the resulting formatting is plain.

**Comment by jkbrzt** [comment]
HTTPie looks at the response `Content-Type` header. If it's `text/plain`, then it doesn't do any special formatting. The URL you provided returns `Content-Type: application/json; charset=utf-8` so it gets properly formatted and highlighted as JSON.

![screen shot 2016-01-03 at 6 58 33 pm](https://cloud.githubusercontent.com/assets/326885/12081021/087a7068-b24c-11e5-8123-98b993019017.png)

**Comment by loretoparisi** [comment]
@jkbrzt exactly. In fact the issue was that the server headers was ```text/plain``` while the body was a text formatted as a json body (well formatted json). Basically the response header ```Content-Type``` is not ```application/json```. Can ```HTTPie``` force json formatting in those cases?
