### ISSUE TITLE
Is there a way to paginate the output while keeping colors and formatting?

### ISSUE THREAD

**Issue by k0pernikus** [jkbrzt/httpie#411]
I have certain HTTP calls the provide a huge response, and fill up quite a few monitor spaces. And in those calls, the most relevant information is at the beginning of the response, so I want to read that first.

So I have to page up quite a few times (or use reverse search in terminal). I rather just view the response on a page-by-page-approach starting from the top.

I tried piping the output of httpie into `less` and `most`, yet thereby I lose both colors and formatting.

Is there a way to get paginated output?

**Comment by k0pernikus** [comment]
Nice, I figured it out on my own. Hitting the manual does help:
```
http --pretty=all POST YOUR_ENDPOINT < scandio-ac.json | less -r
```

**Comment by jkbrzt** [comment]
https://github.com/jkbrzt/httpie#redirected-output

**Comment by vnbrs** [comment]
`http --pretty=all  get https://google.com | less` does it! 😄
