### ISSUE TITLE
XML processing instructions (e.g. xml-stylesheet) lost when formatting

### ISSUE THREAD

**Issue by mgoodhand** [jkbrzt/httpie#415]
I was momentarily confused by the output of `http` for  https://www.xbrl.org/utr/utr.xml 

That URL renders nicely in most browsers as an HTML table, thanks to its reference to render.xsl:

`<?xml-stylesheet type="text/xsl" href="./render.xsl"?>`

Until I looked at the Chrome request/response details and the output from `curl`, I couldn't understand how the rendering was working.

When run in non-pretty mode (e.g. when piped to `head`), the text returned by `http` includes the processing instruction.

It looks like [formatters/xml.py](https://github.com/jkbrzt/httpie/blob/8eb460a6f3925a6020020bf412ccec7342294a60/httpie/output/formatters/xml.py) has code to output the XML declaration, but not processing instructions.

![screen shot 2015-11-23 at 14 14 37](https://cloud.githubusercontent.com/assets/1402660/11338630/2d636efe-91ed-11e5-9fa3-7e4a702cee3c.png)

**Comment by sigmavirus24** [comment]
Sorry, this issue isn't clear. You want `httpie` to render the xml data as a table like the browser does? That would require something that already understands XML stylesheets and what could be a lot of extra processing on `httpie`'s part to find the stylesheet declaration and retrieve the xsl file, and then use it appropriately.

I'm not sure this makes sense for default `httpie` behaviour. A plugin to render this appropriately might work well if you also add `PrettyTable` to do the table rendering.

**Comment by mgoodhand** [comment]
Apologies for the confusion.

The issue is as show in the screenshot: httpie's formatted mode excludes processing instructions.

I'm not asking for a table view. That's just an example of an XSL transform I was struggling to understand because httpie swallowed the processing instruction.

**Comment by sigmavirus24** [comment]
Oh, I completely missed that. Thanks for clarifying @mgoodhand.

**Comment by jkbrzt** [comment]
Please follow #443
