### ISSUE TITLE
Feature Request: Brace Expansion, Range Notation in URLs

### ISSUE THREAD

**Issue by CMCDragonkai** [jkbrzt/httpie#416]
Curl supports a type of range notation or brace expansion which is useful for downloading multiple files.

```
URL  
       The URL syntax is protocol dependent. You’ll find a  detailed  descrip‐
       tion in RFC 3986.

       You  can  specify  multiple  URLs or parts of URLs by writing part sets
       within braces as in:

        http://site.{one,two,three}.com

       or you can get sequences of alphanumeric series by using [] as in:

        ftp://ftp.numericals.com/file[1-100].txt
        ftp://ftp.numericals.com/file[001-100].txt    (with leading zeros)
        ftp://ftp.letters.com/file[a-z].txt

       No nesting of the sequences is supported at the moment, but you can use
       several ones next to each other:

        http://any.org/archive[1996-1999]/vol[1-4]/part{a,b,c}.html

       You  can  specify  any amount of URLs on the command line. They will be
       fetched in a sequential manner in the specified order.

       Since curl 7.15.1 you can also specify step counter for the ranges,  so
       that you can get every Nth number or letter:

        http://www.numericals.com/file[1-100:10].txt
        http://www.letters.com/file[a-z:2].txt
```

I tried using the URL variants in httpie and it didn't work. Perhaps httpie could support it?

**Comment by sigmavirus24** [comment]
> I tried using the URL variants in httpie and it didn't work. Perhaps httpie could support it?

What made you expect that it would work?

For what it's worth, the bit of cURL documentation that you're quoting is a little misleadingly worded. The syntax here is *not* specified as part of RFC 3986. This behaviour is not standardized except in cURL's cli. Any work that httpie would do to detect this would ostensibly break any website which has those characters as part of the URL without the server being aware of this behaviour in cURL/httpie.

The only place this seems potentially reasonable is the `{}` expansion for a hostname but most shells should handle that for you.

**Comment by twopir** [comment]
Can I vote :-1: on this? The entire reason I switched to httpie is that I got sick of shell-quoting AND cURL-escaping the brackets and braces in my URLs.

**Comment by jkbrzt** [comment]
Thanks for the suggestion @CMCDragonkai, but I believe a this is a job for a wrapper script.
