### ISSUE TITLE
RFE: Support html to text format

### ISSUE THREAD

**Issue by tyll** [jkbrzt/httpie#420]
Hi,

I would like to have an option in httpie to support rendering HTML pages as text, for example using html2text:
https://pypi.python.org/pypi/html2text

I you like it, I will try to submit a PR. Do you have a good idea about how to name this formatter?

**Comment by jkbrzt** [comment]
The beauty of CLI tools is that they can be easily combined:

```bash
$ http google.com | html2text
```

```text
# 302 Moved

The document has moved [here](http://www.google.com/).

```

**Comment by tyll** [comment]
Yes, this combination is possible, but it does not create the intended output, since the response headers are now missing. I would like to have output like

```
HTTP/1.1 302 Found
Cache-Control: private
Content-Length: 258
Content-Type: text/html; charset=UTF-8
Date: Sun, 28 Feb 2016 10:05:01 GMT
Location: http://www.google.de/?gfe_rd=cr&ei=TcbSVtj9Kcfj8weQiIOADA

# 302 Moved

The document has moved [here](http://www.google.com/).
```

**Comment by jkbrzt** [comment]
**`http2text`:**

```bash
#!/bin/bash
set -euo pipefail
url="$1"
http --headers --pretty=none "$url"
http "$url" | html2text
```

```bash
$ http2text https://www.google.com/
```

**Comment by tyll** [comment]
Can you maybe explain why you do not want this feature directly in httpie? All the formatting that httpie already supports could be done in external scripts like your's as well. Despite the technical problem with doing two request, which might create contradicting output, for example if there values in the HTML output that are tied to HTTP headers, such as CSRF tokens for session IDs in HTTP cookies, it also makes it harder to describe other people what they need to do to get the same output. It is not just a commandline then but it requires creating a custom shell script.

**Comment by jkbrzt** [comment]
It's because this is a bit of a special use case and such as it's out of the scope of a general CLI HTTP client. All the existing formatting has in common that it makes the output easier to be inspected by humans. You could create a converter plugin but the API isn't really stable nor documented yet. https://github.com/jkbrzt/httpie/blob/master/httpie/plugins/base.py#L52

**Comment by tyll** [comment]
But making it easier to insepect the output for me as a human is exactly the reason why I would like to have the HTML rendered - the plain HTML makes it harder. I would like to use it in penetration tests where I want to modify parameters and see how the page reacts. There thousands of lines of HTML code are a lot harder to read than a short rendered HTML page. Will you ship the plugin with httpie or will it have to be separate? Having all features in one tool makes it easier to write a report about the results that can be reproduced without too much effort.
