### ISSUE TITLE
Response *and* request headers only

### ISSUE THREAD

**Issue by OliverJAsh** [jkbrzt/httpie#425]
I want to output the response *and* request only for the following request: `http://theguardian.com`.

I would like this to include the redirect. This is possible with curl with a simple `curl -vL theguardian.com > /dev/null`.

The `--headers` option provided by httpie has two problems for me:

* No request headers
* No request/response headers for requests before redirects

**Comment by sigmavirus24** [comment]
If this is a feature that is accepted and implemented, I just want to provide a head's up that there are [utility functions for this](https://toolbelt.readthedocs.org/en/latest/dumputils.html) in the [requests-toolbelt](/sigmavirus24/requests-toolbelt).

**Comment by jkbrzt** [comment]
@OliverJAsh To print both request and response headers, you can use `--print=hH`. See section in the README.

As for redirects, printing of them is not implemented as of now. It's a planned feature though, and there's even a pull request somewhere, which I'll look into in the near future.
