### ISSUE TITLE
cant use colon character in file upload field

### ISSUE THREAD

**Issue by xrisk** [jkbrzt/httpie#426]
The \ character is supposed to escape the colon, but apparently it's not working.

`http -f -v ix.io f\:1@test.html`

It sends:

```
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: ix.io
User-Agent: HTTPie/0.9.2
f: 1@test.html
```

**Comment by xrisk** [comment]
The field name should be "f:1".

**Comment by jkbrzt** [comment]
@xrisk you need to properly escape. The single `\` gets eaten already by your shell. You could, for example, additionally wrap the whole string in a pair of single quotes to avoid that. Compare these two commands/outputs to see the difference:

```bash
$ echo f\:1@test.html
f:1@test.html

$ echo 'f\:1@test.html'
f\:1@test.html
```
