### ISSUE TITLE
Enhancement: Can we make the `--auth` argument optional, even when using `--auth-type`?

### ISSUE THREAD

**Issue by hangtwenty** [jkbrzt/httpie#431]
Some recommend against putting sensitive material on your command-line. So it makes sense if we can avoid putting secret keys on command-line, if there is an auth plugin that will load the creds from filesystem or environment variables.

I want to write an auth plugin that does not accept credentials on the command-line. (Instead it will take credentials from a configuration file, like AWS command-line tools do.) Therefore I would like to make the `--auth` argument optional even when using the `--auth-type` argument.

**Comment by hangtwenty** [comment]
I would need to write my own auth plugin to verify but it seems like the `--auth` arg is required even if you force it to be empty ...

Plugin appears to be executed (yes `--auth`):

```
$ http --print=HBbh --auth-type=hmac --auth="foo:secret" google.com
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: HMAC foo:VlEqpanFXMrNc4fw4xopahlGg/+2zUoVEnImr2uI7UM=
Connection: keep-alive
Date: Fri, 22 Jan 2016 03:55:58 GMT
Host: google.com
User-Agent: HTTPie/1.0.0-dev



HTTP/1.1 301 Moved Permanently
Cache-Control: public, max-age=2592000
Content-Length: 219
Content-Type: text/html; charset=UTF-8
Date: Fri, 22 Jan 2016 03:55:59 GMT
Expires: Sun, 21 Feb 2016 03:55:59 GMT
Location: http://www.google.com/
Server: gws
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

and plugin is executed when giving `''` twice for the `--auth` params ...

```
$ http --print=HBbh --auth-type=hmac --auth : google.com
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: HMAC BSa/7aIDwW9yKNevBgRxrPSc48s47RQ3/7yJKfPTcLI=
Connection: keep-alive
Date: Fri, 22 Jan 2016 03:57:39 GMT
Host: google.com
User-Agent: HTTPie/1.0.0-dev



HTTP/1.1 301 Moved Permanently
Cache-Control: public, max-age=2592000
Content-Length: 219
Content-Type: text/html; charset=UTF-8
Date: Fri, 22 Jan 2016 03:57:39 GMT
Expires: Sun, 21 Feb 2016 03:57:39 GMT
Location: http://www.google.com/
Server: gws
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

but no header is added, and plugin is seemingly skipped, with no `--auth` argument.

```
$ http --print=HBbh --auth-type=hmac google.com
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: google.com
User-Agent: HTTPie/1.0.0-dev



HTTP/1.1 301 Moved Permanently
Cache-Control: public, max-age=2592000
Content-Length: 219
Content-Type: text/html; charset=UTF-8
Date: Fri, 22 Jan 2016 03:56:08 GMT
Expires: Sun, 21 Feb 2016 03:56:08 GMT
Location: http://www.google.com/
Server: gws
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
``

**Comment by hangtwenty** [comment]
Meanwhile you cannot do `--auth` with no argument at all. (This makes sense.)

```
$ http --print=HBbh --auth-type=hmac --auth  google.com
usage: http [--json] [--form] [--pretty {all,colors,format,none}]
            [--style STYLE] [--print WHAT] [--verbose] [--headers] [--body]
            [--stream] [--output FILE] [--download] [--continue]
            [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH]
            [--auth USER[:PASS]] [--auth-type {basic,digest,hmac}]
            [--proxy PROTOCOL:PROXY_URL] [--follow] [--verify VERIFY]
            [--cert CERT] [--cert-key CERT_KEY] [--timeout SECONDS]
            [--check-status] [--ignore-stdin] [--help] [--version]
            [--traceback] [--debug]
            [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
http: error: too few arguments
```

**Comment by jkbrzt** [comment]
Related #378

**Comment by hangtwenty** [comment]
Thanks @jkbrzt that's quite helpful!

**Comment by silvexis** [comment]
+1

**Comment by tiyberius** [comment]
+1

**Comment by hangtwenty** [comment]
Is there anything I can do to boost confidence about PR #433 ? Not trying to be a bug, just trying to help if I can. Happy to add further testing (whether unit tests, exploratory tests, etc.)

**Comment by hangtwenty** [comment]
What's the contract with the plugins ... should I test each of the plugins linked in the README, and prove they integrate OK with the changes in #433? Would that be helpful?  Or is that out of scope, because HTTPie is still pre-1.0, and come 1.0 breakage would be a risk anyway? Happy to do what is advised.

**Comment by hangtwenty** [comment]
Well, if we do think that this breaks contract with plugins, it could be that this has the entrypoint: `"httpie.plugins.auth.v2"` rather than `"httpie.plugins.auth.v1"`. Then people could also easily support backwards and forwards compat if they wanted.

I am hoping there is someone on the project who has given extra thought to this kind of thing, and maybe they can chime in with their slant on what would be best. :grinning:

**Comment by hangtwenty** [comment]
Anything I can do to help here?

**Comment by hangtwenty** [comment]
I'd love to get this resolved ... anything I can do to help move the process along? PR build is passing but I'm happy to do other testing or followups; just say the word.

**Comment by ctcampbell** [comment]
+1

**Comment by hangtwenty** [comment]
:champagne:
