### ISSUE TITLE
Regression: unreadable output in httpie 0.9.3

### ISSUE THREAD

**Issue by mgedmin** [jkbrzt/httpie#440]
This is httpie 0.9.2:
![ekrano nuotrauka is 2016-02-15 12-37-21](https://cloud.githubusercontent.com/assets/159967/13046342/e37958ae-d3e0-11e5-9479-f9b2221f2a0e.png)

At this point I decide to see if I'm running the latest version and run `pip install -U httpie`.  I wasn't.

This is httpie 0.9.3:
![ekrano nuotrauka is 2016-02-15 12-37-42](https://cloud.githubusercontent.com/assets/159967/13046354/ee23909e-d3e0-11e5-9222-6fd16faa6085.png)

I cannot read very-light-grey text on a white background.

**Comment by mgedmin** [comment]
There's a workaround: edit `~/.httpie/config.json` and change
```
    "default_options": [],
```
to
```
    "default_options": ["--style=solarized"],
```

**Comment by jkbrzt** [comment]
I see, `monokai` doesn't play well with light background colors. It looks like `solarized` was a better  default color scheme choice.

**Comment by mgedmin** [comment]
I believe [one of the selling features of solarize](http://ethanschoonover.com/solarized#features) is that it works well with both light and dark backgrounds.

**Comment by jkbrzt** [comment]
@mgedmin Changed it back to `solarized`. Thanks!

**Comment by mgedmin** [comment]
Thank you very much!  :heart:
