### ISSUE TITLE
Sending email feature like in curl.

### ISSUE THREAD

**Issue by Johnz86** [jkbrzt/httpie#442]
With Curl you have the option to send an email for example: 
```
curl --url "smtp://localhost:25" --mail-from "username@gmail.com" --mail-rcpt "root@test.sk" --upload-file /tmp/mail.txt
```
If you try 
```
http smtp://localhost:2225
```
You will get:
```
http: error: InvalidSchema: No connection adapters were found for 'smtp://localhost:2225'
```
Is there some adapter so HTTPie supports smtp and sening of emails?

**Comment by jkbrzt** [comment]
@Johnz86 thanks for the suggestion but this is way beyond the scope of a CLI HTTP client
