### ISSUE TITLE
Tomorrow Night Eighties style

### ISSUE THREAD

**Issue by ryansobol** [jkbrzt/httpie#444]
Any chance a tomorrow night eighties style could be added? I promise to be good all year!

https://github.com/MozMorris/tomorrow-pygments/blob/master/styles/tomorrownighteighties.py

**Comment by jkbrzt** [comment]
HTTPie makes all the styles included in Pygments automatically available. So please talk to Pygments maintainers to have Tomorrow Night Eighties included there.

**Comment by ryansobol** [comment]
Okay. 

https://bitbucket.org/birkenfeld/pygments-main/issues/1253/tomorrow-night-eighties-style
