### ISSUE TITLE
Way to process http request without waiting for output/response

### ISSUE THREAD

**Issue by webdotapp** [jkbrzt/httpie#449]
Is there any way to make POST request without waiting for headers and response to make things faster, i just want to ping a API without need of seeing response, as returned response is making request slow.

Please suggest, thanks.

**Comment by jkbrzt** [comment]
If you don't print out the response body then doesn't get downloaded. https://github.com/jkbrzt/httpie#conditional-body-download) 

```bash
$ http --headers http://ipv4.download.thinkbroadband.com/1GB.zip
```

There's no way to avoid waiting for the response headers, though.
