### ISSUE TITLE
Make default colorscheme background independent

### ISSUE THREAD

**Issue by louwers** [jkbrzt/httpie#458]
This is what the output of httpie looks like on black-on-white Terminals:

![image](https://cloud.githubusercontent.com/assets/649392/14233363/a06016dc-f9c6-11e5-8c40-1ad311d0aecf.png)

I'd argue that it makes sense to go for a default colorscheme that is readable regardless of background color (like `git` has, for example). Alternatively, color could be opt-in, like with `ls` and `grep`.

**Comment by louwers** [comment]
'default' as default would be a good option :laughing: 

Black on white:
![screenshot_2016-04-03_21-25-31](https://cloud.githubusercontent.com/assets/649392/14234412/b1d3bea2-f9e2-11e5-92be-4c8939480cac.png)

White on black:
![screenshot_2016-04-03_21-26-05](https://cloud.githubusercontent.com/assets/649392/14234414/b3854fb8-f9e2-11e5-8bc2-0f992f4a121a.png)

**Comment by jkbrzt** [comment]
It was [solarised](http://ethanschoonover.com/solarized) (which is background-independent) until last release, and current master/next release reintroduces it again.
