### ISSUE TITLE
http PUT can only upload 2GB max file 

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [jkbrzt/httpie#460]
http PUT can only upload 2GB max file 

when the file size is lager than 2GB :

http: error: Request timed out (30s).

**Comment by ambujmehra** [comment]
can you put the exact command you running and the complete error message...Thanks

**Comment by zhengxiaochuan-3** [comment]
From: ambujmehra
Date: 2016-04-07 21:31
To: jkbrzt/httpie
CC: Jim Raynor
Subject: Re: [jkbrzt/httpie] http PUT can only upload 2GB max file (#460)
can you put the exact command you running and the complete error message...Thanks

**Comment by zhengxiaochuan-3** [comment]
------------------  success ------------------ 

root@ubuntu:/home/zxc# http  PUT "http://127.0.0.1:888/v1/admin/bucket-1/test" < /tmp/4M 
HTTP/1.1 201 Created
Connection: keep-alive
Content-Type: text/plain;
Date: Fri, 08 Apr 2016 17:13:15 GMT
Server: openresty/1.9.7.3
Transfer-Encoding: chunked


------------------ error ------------------ 

root@ubuntu:/home/zxc# http --debug PUT "http://127.0.0.1:888/v1/admin/bucket-1/test" < /tmp/2.3GB 
HTTPie 0.8.0
HTTPie data: /root/.httpie
Requests 2.2.1
Pygments 1.6
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] linux2


hang forever


Ctrl + C


^CTraceback (most recent call last):
  File "/usr/bin/http", line 9, in <module>
    load_entry_point('httpie==0.8.0', 'console_scripts', 'http')()
  File "/usr/lib/python2.7/dist-packages/httpie/core.py", line 95, in main
    response = get_response(args, config_dir=env.config.directory)
  File "/usr/lib/python2.7/dist-packages/httpie/client.py", line 24, in get_response
    % pformat(requests_kwargs))
  File "/usr/lib/python2.7/pprint.py", line 63, in pformat
    return PrettyPrinter(indent=indent, width=width, depth=depth).pformat(object)
  File "/usr/lib/python2.7/pprint.py", line 122, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/usr/lib/python2.7/pprint.py", line 140, in _format
    rep = self._repr(object, context, level - 1)
  File "/usr/lib/python2.7/pprint.py", line 226, in _repr
    self._depth, level)
  File "/usr/lib/python2.7/pprint.py", line 238, in format
    return _safe_repr(object, context, maxlevels, level)
  File "/usr/lib/python2.7/pprint.py", line 282, in _safe_repr
    vrepr, vreadable, vrecur = saferepr(v, context, maxlevels, level)
  File "/usr/lib/python2.7/pprint.py", line 261, in _safe_repr
    write(qget(char, repr(char)[1:-1]))
KeyboardInterrupt

**Comment by jkbrzt** [comment]
Thanks for the report. I'm currently working on support for streamed uploads so that files of any files could be uploaded.

**Comment by jkbrzt** [comment]
Please follow #461 for progress.

**Comment by luisuimi** [comment]
> http PUT can only upload 2GB max file
> 
> when the file size is lager than 2GB :
> 
> http: error: Request timed out (30s).
