### ISSUE TITLE
Impossible to send an incorrect HTTP method

### ISSUE THREAD

**Issue by strugee** [jkbrzt/httpie#461]
I'm developing a RESTful API and I'm testing it with httpie. Thanks, by the way - this tool is amazing.

However, I'm trying to test the difference between which routes return `405 Method Not Allowed` and which return `501 Not Implemented`. Thus, I went to send a method which obviously wasn't implemented by my server('s framework):

    $ http FOOBAR localhost:3000/moment/57071f9a80fd6f5c447cee03 'Authorization:token foobar'

This returns:

    http: error: ConnectionError: ('Connection aborted.', BadStatusLine("''",)) while doing FOOBAR request to URL: http://localhost:3000/moment/57071f9a80fd6f5c447cee03

Obviously this is not a useful response, as I would expect from httpie.

**Comment by jkbrzt** [comment]
It looks like the server crashed while processing the request due to the unexpected HTTP method, and didn't send an actual HTTP response.

HTTPie does allow you to specify any string as the method:

```bash
$ http -v PEWPEWPEW example.org
```

```http
PEWPEWPEW / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: example.org
User-Agent: HTTPie/0.9.3

…
```

**Comment by strugee** [comment]
Hmm, okay. That may very well be it - my app server didn't crash, but I definitely can imagine something rejecting the connection because of the "bad" method.

Sorry for the noise!
