### ISSUE TITLE
How can i use upload form file without gzip compression?

### ISSUE THREAD

**Issue by Neojoke** [jkbrzt/httpie#462]
I found some apis not support compression,what can I do?
curl is flexible with those apis.

**Comment by Neojoke** [comment]
This is request header output with curl and httpie,
curl can upload form file data correct.
![1](https://cloud.githubusercontent.com/assets/8511328/14553736/cb56414c-031a-11e6-83f4-49f52e1dcd85.png)
![2](https://cloud.githubusercontent.com/assets/8511328/14553737/cb836be0-031a-11e6-88d6-02d60825274d.png)

**Comment by jkbrzt** [comment]
HTTPie doesn't apply gzip compression to uploads.  `Accept-Encoding: gzip, deflate` refers to the accepted *response* encoding types.
