### ISSUE TITLE
Compatible with "request.query_params" method in django-rest-framework

### ISSUE THREAD

**Issue by boylegu** [jkbrzt/httpie#465]
Recently, I writed rest api with django-rest-framework about  http method "GET", and receive data 'request.query_params' in my codes.  But when I run "http GET http://x.x.x.x/name/" tag=xxx", I can't receive params “tag” in requests.
Afterwards，when I can try change  to "request.data", all going well. Finnally, I have to ```request_data = request.query_params.get('tag') or request.data.get('tag')```in my codes.
Is it httpie bug ? 

thanks

**Comment by jkbrzt** [comment]
To specify URL query string parameters, you need to use the  [`key==value`](https://github.com/jkbrzt/httpie#request-url) syntax:

```bash
$ http --verbose httpbin.org/get  tag==xxx  tag2==yyy
```

```http
GET /get?tag=xxx&tag2=yyy HTTP/1.1
```

**Comment by GaryChiang** [comment]
Hi, 
Did you solve this issue? I'm encountering this as well.
