### ISSUE TITLE
install auth plugins via brew

### ISSUE THREAD

**Issue by walery** [jkbrzt/httpie#469]
I'm using brew to install httpie. I would like to add [ntlm-plugin](https://github.com/jkbrzt/httpie-ntlm). Is it possible to do this via brew?

**Comment by sigmavirus24** [comment]
@walery this is something you'd need to do with brew. You'd need a brew recipe and it would need to understand how to install the plugin such that httpie can see it. (The way brew installs python packages makes this tricky if not very difficult.) This isn't the responsibility of httpie.

**Comment by jkbrzt** [comment]
Until the plugin system gets more stable, pip is the simplest way to handle distribution and installation.
