### ISSUE TITLE
Alleviate accepted media-types

### ISSUE THREAD

**Issue by avdv** [jkbrzt/httpie#470]
Currently, the Accept header automatically strictly requires `application/json` responses from the server.

A conformant server should respond with 406 if it cannot deliver the resource using the requested content type.

Setting the Accept header to `application/json` is a too restrictive default, I hereby propose to change it to `application/json, text/json, */*`.

**Comment by avdv** [comment]
Thank you! 😀

**Comment by jbaruch** [comment]
Despite the examples, release notes and everything else 0.9.4 still sends `application/json` only for me:
```
POST /whatever/accepts/json/but/returns/text HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 109
Content-Type: application/json
Host: somehost
User-Agent: HTTPie/0.9.4

{
    "someJson": "here"
}
```
It's probably me, but please advice.

**Comment by jkbrzt** [comment]
@jbaruch it hasn't been released yet
