### ISSUE TITLE
Connection Error : Broken pipe

### ISSUE THREAD

**Issue by YannMoisan** [jkbrzt/httpie#471]
```
$ http --follow --auth xxx:yyy mysite.org token:zzz @file.csv 
http: error: ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))
```

I also tried with
`$ http --follow --auth xxx:yyy mysite.org token:zzz < file.csv 
`

**Comment by jkbrzt** [comment]
It looks like a problem between your computer and `mysite.org`. Feel free to re-open this if the issue persists with a URL to test it again.
