### ISSUE TITLE
Simulate curl --noproxy option

### ISSUE THREAD

**Issue by rpiesnikowski** [jkbrzt/httpie#473]
Hi, 
I've found problem during usage httpie behind corporate proxy. On local machine I'm testing some endpoint, assume **/check**. When I use curl I can call my server:
`curl --noproxy "*" --get -is http://10.108.245.22:8081/check`
But using httpie I receive timeout:
```
http http://10.108.245.22:8081/check --debug
HTTPie 0.8.0
HTTPie data: /home/my-account/.httpie
Requests 2.2.1
Pygments 1.6
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] linux2
>>> requests.request({'allow_redirects': False,
 'auth': None,
 'data': OrderedDict(),
 'files': OrderedDict(),
 'headers': CaseInsensitiveDict({'User-Agent': 'HTTPie/0.8.0'}),
 'method': 'get',
 'params': ParamDict(),
 'proxies': {},
 'stream': True,
 'timeout': 30,
 'url': 'http://10.108.245.22:8081/check',
 'verify': True})
http: error: Request timed out (30s).
```
Please help with that issue,
Regards
Robert

**Comment by jkbrzt** [comment]
It's possible to achieve that using the `$NO_PROXY` environment variable:

```bash
$ NO_PROXY=* http://10.108.245.22:8081/check
```

https://github.com/jkbrzt/httpie#proxies
