### ISSUE TITLE
missing color in v0.9.3

### ISSUE THREAD

**Issue by Cologler** [jkbrzt/httpie#474]
Downloaded from pip.

![](http://i.imgur.com/GnG2NeI.png)

Do any one know what is going on?

**Comment by Arnie97** [comment]
Please try the latest develop version:
```
pip install --upgrade "https://github.com/jkbrzt/httpie/archive/master.zip"
```
我也遇到了这个问题，更新dev版可解决。

**Comment by jkbrzt** [comment]
Please try to update to 0.9.4 and re-open if the issue persists.
