### ISSUE TITLE
Feature idea: pipelining - `http GET /foo`

### ISSUE THREAD

**Issue by SamuelMarks** [jkbrzt/httpie#487]
Just came across this: https://github.com/micha/resty

```
$ resty http://127.0.0.1:8080/data
$ GET /blogs.json
[ {"id" : 1, "title" : "first post", "body" : "This is the first post"}, ... ]
$ PUT /blogs/2.json '{"id" : 2, "title" : "updated post", "body" : "This is the new."}'
{"id" : 2, "title" : "updated post", "body" : "This is the new."}
$ DELETE /blogs/2
$ POST /blogs.json '{"title" : "new post", "body" : "This is the new new."}'
{"id" : 204, "title" : "new post", "body" : "This is the new new."}
```

Would be terminal dependent, but should be straightforward enough to just set an environment variable for the base url and something like `urlparse.urljoin(os.environ['BASE_URL'], **rest)` for it in Python.

If this is of interest I'll work on a PR.

**Comment by jkbrzt** [comment]
@SamuelMarks take a look at [`http-prompt`](https://github.com/eliangcs/http-prompt). It's a wrapper around HTTPie that does something like this.
