### ISSUE TITLE
Support request body in binary format

### ISSUE THREAD

**Issue by tinhtruong** [jkbrzt/httpie#489]
I am testing an Internet Printing Protocol server implementation and there is no way to submit the request body in binary format with 'Content-Type:application/ipp'
HTTPie only support file upload which will set the Content-Type to multipart/form-data.
I have to use curl for now. The command line in curl is as following:
`curl -v --request POST --data-binary "@ValidateJobRequest.bin" --header "Content-Type:application/ipp" --header "Expect:100-continue" http://localhost:10000/ipp`

**Comment by jkbrzt** [comment]
> A universal method for passing request data is through redirected stdin (standard input). Such data is buffered and then with no further processing used as the request body. 
> — https://github.com/jkbrzt/httpie#redirected-input

This is the HTTPie equivalent of the command above:

```bash
http -v :10000/ipp Content-Type:application/ipp Expect:100-continue  < ValidateJobRequest.bin
```
