### ISSUE TITLE
can I use this for a xmlrpc server?

### ISSUE THREAD

**Issue by hackrole** [jkbrzt/httpie#512]
now I was force to debug a php xmlrpc server. Even I hate it, but I have to do the job.
so if this tools support such things?

**Comment by jkbrzt** [comment]
> XML-RPC is a remote procedure call (RPC) protocol which uses XML to encode its calls and **HTTP as a transport mechanism.**
> — https://en.wikipedia.org/wiki/XML-RPC

Yes, you can!

**Comment by hackrole** [comment]
I know this. I mean does the plugin support format request with xmlrpc??
for example:
```
http -j POST http://localhost:8080 a=12 b=11 // for json format
http -f POST http://localhost:8080 a=12 b=11 // for form format
```
I donot see a param for xmlrpc format. write rpc-xml in file dirty my hand too much.

**Comment by jkbrzt** [comment]
If the question isn't "can I use this for a xmlrpc server" but rather "is there any xmlrpc-specific support in" then the answer is a no.
