### ISSUE TITLE
Parsing JSON response

### ISSUE THREAD

**Issue by carlskii** [jkbrzt/httpie#513]
Hi need to extract the API key from my response so that I can chain some HTTP requests. e.g.
```json
{
"APIKey": "98cab291-cc3a-ffc5-fc13-55ca591b42b7", 
"ValidUntil": "/Date(1472126955624)/"
}
```
I can't seem to see how to do this from the docs.

**Comment by sigmavirus24** [comment]
Have you tried out [jq](https://stedolan.github.io/jq/)?

**Comment by carlskii** [comment]
Yes, thats what I’m using now. Was rather hoping to do it in one place rather than having to pipe to another util.

Thanks.

**Comment by jkbrzt** [comment]
@carlskii a feature like this is out of the scope of an HTTP client, but luckily we have the wonderful Unix pipes and jq as @sigmavirus24 points out.

**Comment by abdennour** [comment]
but how i can ignore "curl" which is few MB only and i installed httpie which 69MB.. then after that, i found myself still depending on other 3rd party CLI (.i.e "jq") ?
