### ISSUE TITLE
When using the post sending a request, including &

### ISSUE THREAD

**Issue by Everything2014** [jkbrzt/httpie#514]
#### including &, pipe pp_json no working
![image](https://cloud.githubusercontent.com/assets/6560524/18007092/2e131544-6bd5-11e6-8b25-ec565a1c8e2c.png)

**Comment by jkbrzt** [comment]
`&` is a  special character that instructs bash to run the command before in the background. If you don't want Bash interpreting it as such, you need to quote it or escape it:

http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_03.html

**Comment by Everything2014** [comment]
Like this

http mo-moko.com/go.php date=123\\&hello=123123123 | pp_json

Single quotes, Double quotes like too

Response like, only one param

![image](https://cloud.githubusercontent.com/assets/6560524/18008914/9c091344-6bdc-11e6-9e2b-01e67fcdb963.png)
