### ISSUE TITLE
when i use GET method ,i must use '\' with the '?' if i want to get some params.

### ISSUE THREAD

**Issue by codcodog** [jkbrzt/httpie#517]
i use httpie for GET method, and i use like this:  
http m.zf3.com/saming/send-msg?openId=22
and it tells me that:  
zsh: no matches found: m.zf3.com/saming/send-msg?openId=22
 
i use zsh on archlinux.

but i use like this:  
http m.zf3.com/saming/send-msg\?openId=22
it can work.  

Is it need the '\' parse the '?' when i use GET method to get some params.

**Comment by jkbrzt** [comment]
Yes.

```zsh
% echo m.zf3.com/saming/send-msg?openId=22
zsh: no matches found: m.zf3.com/saming/send-msg?openId=22
```
