### ISSUE TITLE
Get IP address of a website

### ISSUE THREAD

**Issue by 0xAvinash** [jkbrzt/httpie#518]
How can we get the ip address of a website using httpie? I couldn't find any info on httpie documentation.

**Comment by jkbrzt** [comment]
HTTPie currently doesn't show you the iP address, but there other tools you can use for that, for example:

```bash
ping example.org
resolveip example.org
```

**Comment by 0xAvinash** [comment]
can we expect this feature in new revisions?

**Comment by jkbrzt** [comment]
Yes, it will probably become part of the `--verbose, -v` output.

**Comment by 0xAvinash** [comment]
Can we create addon/extensions to httpie? I see the following lines of code does the job
```
import socket

print socket.gethostbyname('google.com')
>> 74.125.236.52
```
