### ISSUE TITLE
Content-based type detection for @files

### ISSUE THREAD

**Issue by constpetrov** [jkbrzt/httpie#530]
When I try to upload file through posting a form like this
`http -a login:pass -f POST https://server.com/attachments data@script`
it doesn't work. It seems that Content-Type wasn't installed properly.
As soon as I rename file to be a .txt file, it works:
`http -a login:pass -f POST https://server.com/attachments data@script.txt`

**Comment by jkbrzt** [comment]
@constpetrov That is correct: the [content type detection](https://github.com/jkbrzt/httpie/blob/64f6f69037082581743a736439be731eb4345f96/httpie/input.py#L631-L643) is based purely on the file extension at the moment. So if it is unknown, or there is none at all, then `Content-Type` doesn't get set. Content-based type detection might come in the future. Related: #175.

**Comment by constpetrov** [comment]
why it doesn't set "multipart/form-data" when I explicitly set -f flag?

**Comment by jkbrzt** [comment]
@constpetrov it does when theres `a@file` — https://httpie.org/docs#file-upload-forms

**Comment by constpetrov** [comment]
> it does when theres a@file 
No, it doesn't if the file has no extension.
I mean, even if the file has no extension BUT there is a -f flag, why don't set `multipart/form-data`?

**Comment by jkbrzt** [comment]
```bash
$ http -fv httpbin.org/post test@/tmp/test
```
```http
POST /post HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 145
Content-Type: multipart/form-data; boundary=8bd1886dda8d45acbf5fb65a5fc8af2c
Host: httpbin.org
User-Agent: HTTPie/1.0.0-dev

--8bd1886dda8d45acbf5fb65a5fc8af2c
Content-Disposition: form-data; name="test"; filename="test"

test

--8bd1886dda8d45acbf5fb65a5fc8af2c--
```
