### ISSUE TITLE
PyPI docs not rendering 

### ISSUE THREAD

**Issue by msabramo** [jkbrzt/httpie#540]
PyPI page used to have beautiful docs but I think a recent update introduced a reST error

https://pypi.python.org/pypi/httpie/0.9.8

**Comment by jkbrzt** [comment]
@msabramo good catch, thanks. Should be fixed now.

**Comment by jkbrzt** [comment]
@msabramo btw, I'm slowly moving httpie plugins to the https://github.com/httpie organization. It would be great if you decided to join in and move there your `[httpie-unixsocket](https://github.com/msabramo/httpie-unixsocket)` as well 👍

**Comment by msabramo** [comment]
Cool! https://pypi.python.org/pypi/httpie looks much better now! Thanks, @jkbrzt!

I wonder if we could add a tox test that validates the reST.

**Comment by msabramo** [comment]
Oh yeah and I can look at moving my plugin to the httpie org
