### ISSUE TITLE
Posting a form field string with spaces results in error

### ISSUE THREAD

**Issue by thornycrackers** [jkbrzt/httpie#548]
I'm currently trying to post to a form and the argument I'm trying to pass is a string with spaces in it.

```
$ http --form POST example.com name="John Smith"
```

But I keep getting this error back:

```
http: error: argument REQUEST_ITEM: "Smith" is not a valid value
```

I've seen this example on a couple of different blogs so it must of worked at some point in time. Am i doing something wrong? 

Debug printout
```
HTTPie 0.9.9
Requests 2.12.4
Pygments 2.1.3
Python 2.7.12 (default, Jun 29 2016, 09:13:05)
[GCC 4.9.2]
/usr/bin/python
Linux 4.4.27-moby

<Environment {
    "colors": 8,
    "config": {
        "__meta__": {
            "about": "HTTPie configuration file",
            "help": "https://httpie.org/docs#config",
            "httpie": "0.9.9"
        },
        "default_options": "[]"
    },
    "config_dir": "/root/.httpie",
    "is_windows": false,
    "stderr": "<open file '<stderr>', mode 'w' at 0x7ff88d3df1e0>",
    "stderr_isatty": true,
    "stdin": "<open file '<stdin>', mode 'r' at 0x7ff88d3df0c0>",
    "stdin_encoding": "UTF-8",
    "stdin_isatty": true,
    "stdout": "<open file '<stdout>', mode 'w' at 0x7ff88d3df150>",
    "stdout_encoding": "UTF-8",
    "stdout_isatty": true
}>
```

**Comment by sigmavirus24** [comment]
This looks like your shell is breaking the two up and HTTPie is receiving "Smith" separately from John. Have you tried doing:


```
http ... name='John Smith'  # or
http ... 'name="John Smith"'
```

**Comment by thornycrackers** [comment]
I tired both of those and no luck unfortunately. I'm not sure why they are getting separated.

**Comment by sigmavirus24** [comment]
@thornycrackers are you interacting with httpie in a shell? If so, what shell are you using? This is a *really* bizarre problem you're having.

**Comment by thornycrackers** [comment]
Now I feel silly, turns out I had forgot about a wrapper script I had written that was doing: 
```
$*
```
instead of:
```
"$@"
```
for passing arguments. Definitely all on my part.
