### ISSUE TITLE
weird behavior of IO redirection

### ISSUE THREAD

**Issue by tonytonyjan** [jkbrzt/httpie#553]
With these commands below:

```
$ http URL > output.txt
$ cat output.txt
```

I expect that `output.txt` should contain headers and body, but only body exists.

I tired

```
$ http URL
```

it output both header and body, and then tried:

```
$ http URL 1>/dev/null
```

It outputs nothing and surprised me, because I thought that headers can be in stderr.

What's going on exactly?

**Comment by malikoth** [comment]
The [docs](https://httpie.org/doc#redirected-output) are very explicit here:

> HTTPie uses a different set of defaults for redirected output than for terminal output. The differences being:
> * Formatting and colors aren't applied (unless --pretty is specified).
> * Only the response body is printed (unless one of the output options is set).
> * Also, binary data isn't suppressed.

The key is that the response body is the only thing printed unless one of the output options is set.  So try setting an output option to define the behavior your expect.

```bash
$ http -hb URL > output.txt
```

**Comment by tonytonyjan** [comment]
@malikoth Thanks you very much. I feel ashamed that I didn't read the doc carefully.
