### ISSUE TITLE
Make msabramo a member of httpie organization?

### ISSUE THREAD

**Issue by msabramo** [jkbrzt/httpie#562]
Hey @jkbrzt,

I just tried to transfer https://github.com/msabramo/httpie-unixsocket to the [`httpie` org](https://github.com/httpie) (as [you had suggested](https://github.com/jkbrzt/httpie/issues/540#issuecomment-265887516)) and I got an error:

<img width="1013" alt="screen shot 2017-02-18 at 7 24 39 pm" src="https://cloud.githubusercontent.com/assets/305268/23098960/2bbc6726-f610-11e6-88aa-55089338cd32.png">

Perhaps you need to make me a member of the httpie organization for that to work?

**Comment by jkbrzt** [comment]
@msabramo sorry, I forgot to invite you — invited now: https://github.com/httpie

**Comment by msabramo** [comment]
Thanks! It worked. Repo was moved to https://github.com/httpie/httpie-unixsocket, as mentioned in https://github.com/httpie/httpie-unixsocket/issues/11
