### ISSUE TITLE
SOCKS support.

### ISSUE THREAD

**Issue by Southern** [jkbrzt/httpie#86]
Any plans for it being supported?

**Comment by joehoyle** [comment]
@jakubroztocil I believe the underlaying now has SOCKS support?

**Comment by jakubroztocil** [comment]
@joehoyle based on what?

**Comment by sigmavirus24** [comment]
@joehoyle it does not

**Comment by joehoyle** [comment]
Ahh, my bad - the relevant PR was closed, not merged - seems this is the most recent attempt https://github.com/shazow/urllib3/pull/486
