### ISSUE TITLE
Option to force pretty output on response, regardless of Content-type.

### ISSUE THREAD

**Issue by RogWilco** [jkbrzt/httpie#92]
I'm noticing a few places where the response headers are coming back with a Content-type of "text/html" when they actually contain JSON. It would be nice if, in cases like these, you could somehow specify a format to "force" on the response so that the body could still be prettified.

**Comment by kfix** [comment]
see #368

**Comment by jkbrzt** [comment]
Now with the `--json, -j` option HTTPie tries to detect JSON responses when the `Content-Type` is unknown or `text/plain`.

**Comment by dflock** [comment]
> Now with the --json, -j option HTTPie tries to detect JSON responses when the Content-Type is unknown or text/plain.

Right, but there's still no way to force it, so if the Content-Type is `text/html` but the content is JSON, then you're still out of luck - you have to pip through `jq` or something.
