### ISSUE TITLE
Add option to force SSL/TLS version

### ISSUE THREAD

**Issue by hannesg** [jkbrzt/httpie#98]
Hi

I currently have to work with a load balancer that only supports SSLv3 correctly. With curl I can use the "-3" switch to enforce using that, but httpie doesn't have an option for that. Please add a commandline switch to forcibly select the SSL/TLS version to use.

Thank You
Hannes

**Comment by jtka** [comment]
If web server is configured only allow TLS1.2 (e.g. in apache SSLProtocol +TLSv1.2), requests fails:

http https://webserver.localhost
http: error: SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:600) while doing GET request to URL: https://webserver.localhost/

So, it would be nice to have similar option as curl to select SSL/TLS protocol version:
 -2, --sslv2         Use SSLv2 (SSL)
 -3, --sslv3         Use SSLv3 (SSL)
 -1, --tlsv1         Use => TLSv1 (SSL)
     --tlsv1.0       Use TLSv1.0 (SSL)
     --tlsv1.1       Use TLSv1.1 (SSL)
     --tlsv1.2       Use TLSv1.2 (SSL)

**Comment by hlascelles** [comment]
This was subsequently added. To test if your site supports the deprecated TLS 1.1 mode, use:

```
https "https://www.foo.com" --ssl=tls1.1
```

**Comment by jakubroztocil** [comment]
Yes, this feature has been added. Docs: https://httpie.io/docs#https
